apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: zomatoapp
  name: zomatoapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zomatoapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: zomatoapp
    spec:
      containers:
      - image: tolase/zomato:zomatoapp
        name: zomato
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: zomatoapp